sonata_media:
    class:
        media: Nanotech\MediaBundle\Entity\Media
        gallery:  Nanotech\MediaBundle\Entity\Gallery
        gallery_has_media:  Nanotech\MediaBundle\Entity\GalleryHasMedia
   
    providers:
        file:
            service:    sonata.media.provider.file
            resizer:    false
            filesystem: sonata.media.filesystem.local
            cdn:        sonata.media.cdn.server
            generator:  sonata.media.generator.default
            thumbnail:  sonata.media.thumbnail.format
            allowed_extensions: ['pdf', 'txt', 'rtf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pttx', 'odt', 'odg', 'odp', 'ods', 'odc', 'odf', 'odb', 'csv', 'xml']
            allowed_mime_types: ['application/pdf', 'application/x-pdf', 'application/rtf', 'text/html', 'text/rtf', 'text/plain']

        image:
            service:    sonata.media.provider.image
            resizer:    sonata.media.resizer.simple # sonata.media.resizer.square
            filesystem: sonata.media.filesystem.local
            cdn:        sonata.media.cdn.server
            generator:  sonata.media.generator.default
            thumbnail:  sonata.media.thumbnail.format
            allowed_extensions: ['jpg', 'png', 'jpeg']
            allowed_mime_types: ['image/pjpeg', 'image/jpeg', 'image/png', 'image/x-png']

       
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: image_banniere # you need to set a context
    contexts:
                
        image_banniere:  
            providers:
                - sonata.media.provider.image         
            formats:
                big:  { width: 2048 ,height: 1024 , quality: 100}
    
        image_logo:  
            providers:
                - sonata.media.provider.image        
            formats:
                big:  { width: 400 ,height: 400 , quality: 100}
                
                
        pdf_planning:  
            providers:
                - sonata.media.provider.file                
        
        image_partenaire:  
            providers:
                - sonata.media.provider.image        
            formats:
                big:  { width: 1200 ,height: 800 , quality: 100}
      
    cdn:
        server:
            path: "%media_path%" 

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media" 
            create:     true
     
