nanotech_canhebergement_service:
    resource: "@NanotechCanhebergementBundle/Controller/ServiceController.php"
    type:     annotation

nanotech_canhebergement:
    resource: "@NanotechCanhebergementBundle/Resources/config/routing.yml"
    prefix:   /

nanotech_canhebergement_client:
  resource: "@NanotechCanhebergementBundle/Resources/config/routingclient.yml"
  prefix:   /client

nanotech_canhebergement_admin:
  resource: "@NanotechCanhebergementBundle/Resources/config/routingadmin.yml"
  prefix:   /admin

nanotech_media:
    resource: "@MediaBundle/Resources/config/routing.yml"
    prefix:   /nanoMedia
    
    
NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix: /api/doc

fos_oauth_server_token:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
  
sonata_api_media:
    type:         rest
    prefix:       /api
    resource:     "@SonataMediaBundle/Resources/config/routing/api.xml"


canhegergement_api:
  resource: "@NanotechCanhebergementBundle/Resources/config/api_routing.yml"
  prefix: /api

fos_user_register:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix: /register

fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /resetting

fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /profile


admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
    
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# fosjsrouting
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

