security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        
    role_hierarchy:
        ROLE_SONATA_CANHEBERGEMENT_PARTENAIRE:
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PARTENAIRE_LIST
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PARTENAIRE_VIEW
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PARTENAIRE_EDIT

        ROLE_SONATA_CANHEBERGEMENT_CARTEBAR:
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_CARTE_BAR_LIST
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_CARTE_BAR_VIEW
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_CARTE_BAR_EDIT
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_CARTE_BAR_DELETE
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_CARTE_BAR_CREATE

        ROLE_SONATA_CANHEBERGEMENT_CARTERESTAURANT:
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_CARTE_RESTAURANT_LIST
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_CARTE_RESTAURANT_VIEW
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_CARTE_RESTAURANT_EDIT
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_CARTE_RESTAURANT_DELETE
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_CARTE_RESTAURANT_CREATE

        ROLE_SONATA_CANHEBERGEMENT_PLANNING:
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PLANNING_LIST
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PLANNING_VIEW
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PLANNING_CREATE

        ROLE_SONATA_CANHEBERGEMENT_PIECE:
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PIECE_LIST
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PIECE_VIEW
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PIECE_EDIT
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PIECE_DELETE
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PIECE_CREATE

        ROLE_SONATA_CANHEBERGEMENT_RESERVATION:
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_RESERVATION_LIST
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_RESERVATION_VIEW
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_RESERVATION_EDIT
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_RESERVATION_CREATE

        ROLE_SONATA_CANHEBERGEMENT_RESERVATION_CONFIRME:
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_RESERVATION_CONFIRME_LIST
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_RESERVATION_CONFIRME_VIEW
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_RESERVATION_CONFIRME_EDIT
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_RESERVATION_CONFIRME_CREATE

        ROLE_SONATA_CANHEBERGEMENT_PAYER:
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PAYER_LIST
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PAYER_VIEW

        ROLE_SONATA_CANHEBERGEMENT_UTILISATEUR:
            - ROLE_CANHEBERGEMENT_ADMIN_ADMIN_UTILISATEUR_LIST
            - ROLE_CANHEBERGEMENT_ADMIN_ADMIN_UTILISATEUR_VIEW
            - ROLE_CANHEBERGEMENT_ADMIN_ADMIN_UTILISATEUR_EDIT
            - ROLE_CANHEBERGEMENT_ADMIN_ADMIN_UTILISATEUR_CREATE
            - ROLE_CANHEBERGEMENT_ADMIN_ADMIN_UTILISATEUR_DELETE
            
        ROLE_SONATA_CANHEBERGEMENT_CATEGORIE:
            - ROLE_CANHEBERGEMENT_ADMIN_ADMIN_CATEGORIE_LIST
            - ROLE_CANHEBERGEMENT_ADMIN_ADMIN_CATEGORIE_VIEW
            - ROLE_CANHEBERGEMENT_ADMIN_ADMIN_CATEGORIE_EDIT
            - ROLE_CANHEBERGEMENT_ADMIN_ADMIN_CATEGORIE_CREATE
            - ROLE_CANHEBERGEMENT_ADMIN_ADMIN_CATEGORIE_DELETE

        ROLE_SONATA_CANHEBERGEMENT_BANNIERE:
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_BANNIERE_LIST
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_BANNIERE_VIEW
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_BANNIERE_EDIT
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_BANNIERE_DELETE
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_BANNIERE_CREATE

        ROLE_SONATA_CANHEBERGEMENT_COMMANDEBAR:
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_COMMANDE_BAR_LIST
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_COMMANDE_BAR_VIEW

        ROLE_SONATA_CANHEBERGEMENT_GALLERY:
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_GALLERY_ALL


        ROLE_SONATA_CANHEBERGEMENT_COMMANDERESTAURANT:
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_COMMANDE_RESTAURANT_LIST
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_COMMANDE_RESTAURANT_VIEW

        ROLE_SONATA_CANHEBERGEMENT_COMMENTAIRE:
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_COMMENTAIRE_LIST
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_COMMENTAIRE_VIEW
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_COMMENTAIRE_DELETE

        ROLE_SONATA_CANHEBERGEMENT_COMMENTAIRECLIENT:
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_COMMENTAIRE_CLIENT_LIST
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_COMMENTAIRE_CLIENT_VIEW
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_COMMENTAIRE_CLIENT_EDIT
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_COMMENTAIRE_CLIENT_DELETE
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_COMMENTAIRE_CLIENT_CREATE

        ROLE_SONATA_CANHEBERGEMENT_INTERNAUTE:
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_INTERNAUTE_LIST
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_INTERNAUTE_VIEW
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_INTERNAUTE_EDIT
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_INTERNAUTE_DELETE
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_INTERNAUTE_CREATE

        ROLE_SONATA_CANHEBERGEMENT_MOYENPAIEMENT:
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_MOYENPAIEMENT_LIST
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_MOYENPAIEMENT_VIEW
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_MOYENPAIEMENT_EDIT
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_MOYENPAIEMENT_DELETE
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_MOYENPAIEMENT_CREATE

        ROLE_SONATA_CANHEBERGEMENT_PARAMETRE:
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PARAMETRE_LIST
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PARAMETRE_VIEW
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PARAMETRE_EDIT
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PARAMETRE_DELETE
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PARAMETRE_CREATE

        ROLE_SONATA_CANHEBERGEMENT_PROXIMITE:
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PROXIMITE_LIST
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PROXIMITE_VIEW
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PROXIMITE_EDIT
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PROXIMITE_DELETE
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PROXIMITE_CREATE

        ROLE_SONATA_CANHEBERGEMENT_SERVICE:
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_SERVICE_LIST
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_SERVICE_VIEW
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_SERVICE_EDIT
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_SERVICE_DELETE
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_SERVICE_CREATE

        ROLE_INTERNAUTE: 
            - ROLE_INTERNAUTE

        ROLE_CONNEXION:
#            - ROLE_CONNEXION

        ROLE_RECEPTION:
#            - ROLE_RECEPTION
            - ROLE_SONATA_CANHEBERGEMENT_RESERVATION
            - ROLE_SONATA_CANHEBERGEMENT_RESERVATION_CONFIRME
            - ROLE_SONATA_CANHEBERGEMENT_PAYER
#            - ROLE_CONNEXION

        ROLE_SERVICE:
#            - ROLE_SERVICE
            - ROLE_SONATA_CANHEBERGEMENT_PLANNING
#            - ROLE_CONNEXION

        ROLE_PARTENAIRE:
            - ROLE_SONATA_CANHEBERGEMENT_GALLERY
            - ROLE_SONATA_CANHEBERGEMENT_PARTENAIRE
            - ROLE_SONATA_CANHEBERGEMENT_UTILISATEUR
            - ROLE_SONATA_CANHEBERGEMENT_CARTEBAR
            - ROLE_SONATA_CANHEBERGEMENT_CARTERESTAURANT
            - ROLE_SONATA_CANHEBERGEMENT_PIECE
#            - ROLE_PARTENAIRE
            - ROLE_RECEPTION
            - ROLE_SERVICE
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PLANNING_EDIT
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PLANNING_DELETE
            - ROLE_SONATA_CANHEBERGEMENT_COMMENTAIRE
            - ROLE_SONATA_CANHEBERGEMENT_COMMANDEBAR
            - ROLE_SONATA_CANHEBERGEMENT_COMMANDERESTAURANT
            - ROLE_SONATA_ADMIN

        ROLE_ADMIN:
            - ROLE_PARTENAIRE
            - ROLE_SONATA_CANHEBERGEMENT_SERVICE
            - ROLE_SONATA_CANHEBERGEMENT_PROXIMITE
            - ROLE_SONATA_CANHEBERGEMENT_PARAMETRE
            - ROLE_SONATA_CANHEBERGEMENT_MOYENPAIEMENT
            - ROLE_SONATA_CANHEBERGEMENT_INTERNAUTE
            - ROLE_SONATA_CANHEBERGEMENT_COMMENTAIRE
            - ROLE_SONATA_CANHEBERGEMENT_COMMENTAIRECLIENT
            - ROLE_SONATA_CANHEBERGEMENT_BANNIERE
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PAYER_DELETE
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PAYER_EDIT
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_RESERVATION_CONFIRME_DELETE
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_RESERVATION_DELETE
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PARTENAIRE_CREATE
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_PARTENAIRE_DELETE
            - ROLE_NANOTECH_CANHEBERGEMENT_ADMIN_ADMIN_COMMENTAIRE_CREATE


        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_SUPER_ADMIN
            - ROLE_ALLOWED_TO_SWITCH

    access_decision_manager:
        strategy: unanimous

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email        # fos_user.user_provider.username_email does not seem to work (OAuth-spec related ("username + password") ?)
    firewalls:
        oauth_token:                                   # Everyone can access the access token URL.
            pattern: ^/oauth/v2/token
            security: false
        doc:
            pattern: ^/api/doc
            security: false
            
        api:
            pattern: ^/api                               # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true                          # Anonymous access is not allowed
        
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
                default_target_path: /admin
            logout:       true
            anonymous:    true


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin, role: ROLE_CONNEXION }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
