nanotech_canhebergement_homepage:
    path:     /
    defaults: { _controller: NanotechCanhebergementBundle:Default:index }

nanotech_canhebergement_hotel:
    path:     /hotel
    defaults: { _controller: NanotechCanhebergementBundle:Default:hotel }
    
nanotech_canhebergement_reserver:
    path:     /reserver
    defaults: { _controller: NanotechCanhebergementBundle:Default:reservation }