nanotech_canhebergement_homepage:
    path:     /
    defaults: { _controller: NanotechCanhebergementBundle:Default:index }

nanotech_canhebergement_hotel:
    path:     /hotel
    defaults: { _controller: NanotechCanhebergementBundle:Default:hotel }
    
nanotech_canhebergement_reserver:
    path:     /reserver
    defaults: { _controller: NanotechCanhebergementBundle:Default:reservation }
    
nanotech_canhebergement_recherche:
    path:     /recherche
    defaults: { _controller: NanotechCanhebergementBundle:Default:recherche }
    
nanotech_canhebergement_recherchemaison:
    path:     /recherche
    defaults: { _controller: NanotechCanhebergementBundle:Default:recherchemaison }
    
nanotech_canhebergement_inscription:
    path:     /inscription
    defaults: { _controller: NanotechCanhebergementBundle:Default:inscription }