nanotech_canhebergement_homepage:
    path:     /
    defaults: { _controller: NanotechCanhebergementBundle:Index:index }

nanotech_canhebergement_hotel:
    path:     /hotel/{slug}
    defaults: { _controller: NanotechCanhebergementBundle:Partenaire:index }


nanotech_canhebergement_commentaire:
    path:     /hotel/{slug}/{nombre}
    defaults: { _controller: NanotechCanhebergementBundle:Partenaire:commmentaire }


nanotech_canhebergement_reserver:
    path:     /reserver
    defaults: { _controller: NanotechCanhebergementBundle:Default:reservation }
    
nanotech_canhebergement_recherche:
    path:     /recherche
    defaults: { _controller: NanotechCanhebergementBundle:Default:recherche }
    
nanotech_canhebergement_recherchemaison:
    path:     /recherche
    defaults: { _controller: NanotechCanhebergementBundle:Default:recherchemaison }
    

nanotech_canhebergement_form_inscription:
    path:     /login
    defaults: { _controller: NanotechCanhebergementBundle:Inscription:inscription }
    methods: POST

nanotech_canhebergement_result_recherche:
    path:     /result_hotel
    defaults: { _controller: NanotechCanhebergementBundle:Default:recherchemaison }
    methods: GET