<?php

namespace Nanotech\CanhebergementBundle\Repository;

/**
 * BanniereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BanniereRepository extends \Doctrine\ORM\EntityRepository
{
}
