<?php

namespace Nanotech\CanhebergementBundle\Repository;

/**
 * CarteBarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteBarRepository extends \Doctrine\ORM\EntityRepository
{
}
