<?php

namespace Nanotech\CanhebergementBundle\Repository;

/**
 * CarteRestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteRestaurantRepository extends \Doctrine\ORM\EntityRepository
{
}
