<?php

namespace Nanotech\CanhebergementBundle\Repository;

/**
 * CommandeBarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeBarRepository extends \Doctrine\ORM\EntityRepository
{
}
