<?php

namespace Nanotech\CanhebergementBundle\Repository;

/**
 * CommandeRestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRestaurantRepository extends \Doctrine\ORM\EntityRepository
{
}
