<?php

namespace Nanotech\CanhebergementBundle\Repository;

/**
 * PayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayerRepository extends \Doctrine\ORM\EntityRepository
{
}
