<?php

namespace Nanotech\CanhebergementBundle\Repository;


/**
 * PieceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLikeQueryBuilder($pattern)
    {
        return $this
            ->createQueryBuilder('c')
            ->where('c.partenaire = :pattern')
            ->setParameter('pattern', $pattern)
            ;
    }
}
