<?php

namespace Nanotech\CanhebergementBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProximiteRepository extends \Doctrine\ORM\EntityRepository
{
}
