<?php

namespace Nanotech\CanhebergementBundle\Repository;

/**
 * ReservationConfirmeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationConfirmeRepository extends \Doctrine\ORM\EntityRepository
{
}
